version: '3.8'

services:
  llm:
    build:
      context: .
    container_name: llm
    ports:
      - "5000:5000"  # Map host port 5001 to container port 5000
    networks:
      - waffle_house_network

networks:
  waffle_house_network:
    external: bridge